// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/nicopellerin/virtual-canvas-api/graph/models"
)

type AddArtworkInput struct {
	ID string `json:"id"`
}

type AuthResponse struct {
	AuthToken *AuthToken   `json:"authToken"`
	User      *models.User `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type LoginUserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type PublicProfile struct {
	ID       string          `json:"id"`
	Email    string          `json:"email"`
	Username string          `json:"username"`
	Images   []*models.Image `json:"images"`
	Social   *models.Social  `json:"social"`
}

type SignupUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type UsernameInput struct {
	Username string `json:"username"`
}
